base_model: unsloth/Meta-Llama-3.1-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: chatml
datasets:
  - path: Howard881010/climate-4day
    type: alpaca
    train_on_split: train
dataset_prepared_path:
output_dir: ./finetune/output/climate-4day

test_datasets:
  - path: Howard881010/climate-4day
    split: valid
    type: alpaca

adapter: lora
lora_model_dir:

sequence_len: 2600
sample_packing: false
pad_to_sequence_len: true

lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: finetune
wandb_entity:
wandb_watch:
wandb_name: climate-4day
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 4
num_epochs: 3
optimizer: adamw_hf
learning_rate: 0.00002
max_grad_norm: 1.0

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
logging_steps: 1
xformers_attention: 
flash_attention: true
eval_sample_packing: False

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
weight_decay: 0.0
seed: 0
special_tokens:
  pad_token: "<|end_of_text|>"
