# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama3-70b-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi  # Adjust the size as needed
