# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kai-vllm-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi # Adjust the size as needed
