project_name: multimodal
namespace: spatiotemporal-decision-making
user: howard
registry_host: gitlab-registry.nrp-nautilus.io
ssh_host: gitlab-ssh.nrp-nautilus.io
ssh_port: 30622
conda_home: /opt/conda
image: gitlab-registry.nrp-nautilus.io/howard/multimodal:latest
gpu_whitelist:
  - NVIDIA-GeForce-RTX-3090
  - NVIDIA-A10
hostname_whitelist:
  # - node-2-2.sdsc.optiputer.net
  - node-1-4.sdsc.optiputer.net
  # - node-2-1.sdsc.optiputer.net
  # - gp-engine.beocat.ksu.edu
  # - sphinx.sdstate.edu
  # - k8s-a6000-02.calit2.optiputer.net
  # - gpn-fiona-mizzou-6.rnet.missouri.edu
  # - gpn-fiona-mizzou-5.rnet.missouri.edu
  # - rci-nrp-gpu-04.sdsu.edu
  # - hcc-prp-c5038.unl.edu
  # - hcc-prp-c5036.unl.edu
  # - gpu-02.nrp.mghpcc.org
  # - gpengine-uark.areon.net
  # - hcc-gpn-argo-1.unl.edu
  # - k8s-a40-01.calit2.optiputer.net
  # - hcc-gpengine-shor-c5303.unl.edua