project_name: multimodal
model:
  mistral7b:
    command: >
      git checkout . &&
      git pull &&
      python -m axolotl.cli.preprocess finetune/finance_summary.yml &&
      accelerate launch -m axolotl.cli.train finetune/finance_summary.yml && 
      s5cmd cp finetune/outputs/climate-numerical-finetune s3://multimodal_fine_tuning
    cpu_count: 8
    gpu_count: 8
    memory: 30
dataset:
  yelp:
    hparam:
      _fn: Howard881010/Yelp-dataset
  mimic:
    hparam:
      _fn: mimic.txt
run:
  model: [mistral7b]
  dataset: [yelp]
# file:
#   - ./axolotl/examples/llama-2/myconfig.yml
hostname_whitelist:
  - hcc-chase-shor-c4719.unl.edu
