project_name: multimodal
model:
  mistral7b:
    command: CUDA_VISIBLE_DEVICES="" python -m axolotl.cli.preprocess finetune/qlora.yml &&
             accelerate launch -m axolotl.cli.train finetune/qlora.yml
    cpu_count: 5
    gpu_count: 8
    memory: 20
dataset:
  yelp:
    hparam:
      _fn: Howard881010/Yelp-dataset
  mimic:
    hparam:
      _fn: mimic.txt
run:
  model: [mistral7b]
  dataset: [yelp]
# file:
#   - ./axolotl/examples/llama-2/myconfig.yml