project_name: multimodal
model:
  mistral7b:
    command: CUDA_VISIBLE_DEVICES="" python -m axolotl.cli.preprocess axolotl/examples/llama-2/qlora.yml &&
             accelerate launch -m axolotl.cli.train axolotl/examples/llama-2/qlora.yml && 
             s3cmd put --recursive axolotl/outputs/qlora-out s3://multimodal_fine_tuning/
    cpu_count: 5
    memory: 20
dataset:
  yelp:
    hparam:
      _fn: Howard881010/Yelp-dataset
  mimic:
    hparam:
      _fn: mimic.txt
run:
  model: [mistral7b]
  dataset: [yelp]
# file:
#   - ./axolotl/examples/llama-2/myconfig.yml