project_name: multimodal
model:
  finance-summary:
    command: >
      git checkout . &&
      git pull &&
      sudo apt update &&
      sudo apt install -y libaio-dev &&
      python -m axolotl.cli.preprocess finetune/finance_numerical.yml &&
      accelerate launch -m axolotl.cli.train finetune/finance_numerical.yml && 
      s5cmd cp finetune/outputs/finance-numerical-finetune s3://multimodal_fine_tuning
    cpu_count: 8
    gpu_count: 6
    memory: 30
dataset:
  yelp:
    hparam:
      _fn: Howard881010/Yelp-dataset
  mimic:
    hparam:
      _fn: mimic.txt
run:
  model: [finance-summary]
  dataset: [yelp]
# file:
#   - ./axolotl/examples/llama-2/myconfig.yml
hostname_whitelist:
  - hcc-chase-shor-c4719.unl.edu
