project_name: multimodal
model:
  mistral7b:
    command: >
      python -m axolotl.cli.preprocess finetune/climate.yml &&
      accelerate launch -m axolotl.cli.train finetune/climate.yml && 
      s5cmd cp -r finetune/outputs/climate-finetune s3://multimodal_fine_tuning
    cpu_count: 5
    gpu_count: 4
    memory: 20
dataset:
  yelp:
    hparam:
      _fn: Howard881010/Yelp-dataset
  mimic:
    hparam:
      _fn: mimic.txt
run:
  model: [mistral7b]
  dataset: [yelp]
# file:
#   - ./axolotl/examples/llama-2/myconfig.yml
hostname_whitelist:
  - ry-gpu-03.sdsc.optiputer.net
